services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project_settings.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project_settings.settings
      - key: PYTHONUNBUFFERED
        value: "true"
    staticPublishPath: staticfiles
    volumes:
      - name: django-data
        path: /var/data
